local_backend:
  url: http://localhost:8081/api/v1
backend:
  #name: git-gateway
  #branch: master
  # name: test-repo
  name: proxy
  branch: master
  proxy_url: https://vsuk0-8081.sse.codesandbox.io/api/v1
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "area"
    label: "国家/地区"
    folder: "data/area"
    slug: "{{fields.countryCode}}"
    identifier_field: slug
    create: true
    format: yml
    fields:
      - name: title
        label: 名称
      - name: countryCode
        label: 代码
        hint: 如us, cn等。

  - name: "institute"
    label: "学校"
    folder: "data/institute"
    path: "{{fields.countryCode}}/{{slug}}"
    create: true
    format: yml
    identifier_field: slug
    slug: "{{fields.slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - name: slug
        label: SLUG
      - name: name
        label: Name
      - name: countryCode
        label: 国家/地区
        widget: "relation"
        collection: "area"
        searchFields: ["title", "countryCode"]
        valueField: "countryCode"
        displayFields: ["title"]
      - name: website
        widget: string
  
  - name: "update"
    label: "资讯"
    folder: "data/update"
    path: "{{year}}-{{month}}/{{slug}}"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布时间", name: "date", widget: "datetime"}
      - {label: "外部链接", name: "link", widget: "string"}
      - {label: "概要", name: "description", widget: "text", required: false}
      - {label: "推荐", name: "featuredpost", widget: "boolean", required: false}
      - {label: "标题图片", name: "featuredimage", widget: image, required: false}
      - {label: "正文", name: "body", widget: "markdown", required: false}
      - {label: "标签", name: "tags", widget: "list"}
      - name: instituteSlug
        label: 学校
        widget: "relation"
        collection: "institute"
        searchFields: ["name", "slug"]
        valueField: "slug"
        displayFields: ["name"]
        required: false
      - name: countryCode
        label: 国家/地区
        widget: "relation"
        collection: "area"
        searchFields: ["title", "countryCode"]
        valueField: "countryCode"
        displayFields: ["title"]
        required: false
      - {label: "来源", name: source, widget: "string", required: false}

  - name: "article"
    label: "资料"
    folder: "data/article"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布时间", name: "date", widget: "datetime"}
      - {label: "外部链接", name: "link", widget: "string"}
      - {label: "概要", name: "description", widget: "text", required: false}
      - {label: "推荐", name: "featuredpost", widget: "boolean", required: false}
      - {label: "标题图片", name: "featuredimage", widget: image, required: false}
      - {label: "正文", name: "body", widget: "markdown", required: false}
      - {label: "标签", name: "tags", widget: "list"}
      - name: instituteSlug
        label: 学校
        widget: "relation"
        collection: "institute"
        searchFields: ["name", "slug"]
        valueField: "slug"
        displayFields: ["name"]
        required: false
      - name: countryCode
        label: 国家/地区
        widget: "relation"
        collection: "area"
        searchFields: ["title", "countryCode"]
        valueField: "countryCode"
        displayFields: ["title"]
        required: false
      - {label: "来源", name: source, widget: "string", required: false}

  # - name: "blog"
  #   label: "Blog"
  #   folder: "src/pages/blog"
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields:
  #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Description", name: "description", widget: "text"}
  #     - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
  #     - {label: "Featured Image", name: "featuredimage", widget: image}
  #     - {label: "Body", name: "body", widget: "markdown"}
  #     - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "页面"
    files:
      - file: "pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [
              {label: Title, name: title, widget: string}, 
              {label: Description, name: description, widget: text}
            ]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [
              {label: Heading, name: heading, widget: string}, 
              {label: Description, name: description, widget: text},
              {label: Blurbs, name: blurbs, widget: list, fields: [
                {label: Image, name: image, widget: image}, 
                {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      # - file: "src/pages/products/index.md"
      #   label: "Products Page"
      #   name: "products"
      #   fields:
      #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
      #     - {label: Title, name: title, widget: string}
      #     - {label: Image, name: image, widget: image}
      #     - {label: Heading, name: heading, widget: string}
      #     - {label: Description, name: description, widget: string}
      #     - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      #     - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      #     - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      #     - {label: Full_image, name: full_image, widget: image}
      #     - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
