name: publish-gh-pages

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: drumlab/gatsby-gh-pages-action@v3.2
        env:
          GATSBY_PATH_PREFIX: /covid19-datahub
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
