name: publish-gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: drumlab/gatsby-gh-pages-action@149ac375c74864f6d36df43266d167958ee43fcd
        env:
          GATSBY_PATH_PREFIX: /covid19-datahub
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
