name: validate-pull-request

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: drumlab/gatsby-gh-pages-action@v3
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          skip-publish: true
